-- Run in the Supabase SQL editor. All data is fictional.
-- Re-running the seed does not duplicate rows or overwrite existing records.
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  major text not null,
  created_at timestamptz not null default now()
);

insert into public.students (name, email, major) values
  ('Prad', 'prad.cs@example.com', 'Computer Science'),
  ('Maya Chen', 'maya@example.com', 'Mechanical Engineering'),
  ('Prad', 'prad.math@example.com', 'Mathematics'),
  ('Jordan Lee', 'jordan@example.com', 'Economics'),
  ('Sofia Patel', 'sofia@example.com', 'Bioengineering'),
  ('Prad', 'prad.physics@example.com', 'Physics'),
  ('Alex Rivera', 'alex@example.com', 'Architecture'),
  ('Sam Nguyen', 'sam@example.com', 'Statistics'),
  ('Nia Brooks', 'nia@example.com', 'Computer Science')
on conflict (email) do nothing;

-- The public/publishable key can read only this fictional workshop dataset.
-- Do not use this public-read policy for real student information.
alter table public.students enable row level security;
revoke all on table public.students from anon, authenticated;
grant select on table public.students to anon, authenticated;
drop policy if exists "Workshop students are readable" on public.students;
create policy "Workshop students are readable" on public.students
  for select to anon, authenticated using (true);
